---
title: "STA640 final"
author: "Shuo Wang"
date: "4/22/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(glmnet)
library(tidyverse)
library(caret)
library(kableExtra)
```

## design
### Simulate Data
```{r}
sim_data1 = function(N, K = c(10, 20, 30)){
  epsilon = matrix(rnorm(40*N), nrow = N)
  epsilon[,2*(1:10)] = 
    matrix(rpois(N*10, seq(7,7,length.out=10)), ncol = 10, byrow = TRUE)
  data = lapply(K, function(k){
    x = epsilon[,seq_len(k)]
    #x = cbind(x, matrix(0.5 * rnorm(k*N), nrow = N))
    #x = t(t(x) - 0.1*(1:2*k))
    y = 3 + apply(x[,seq_len(k)], 1, function(i){
      sum(i[1:(k/2)]*2) + sum(i[(k/2+1):length(i)]*0.01)
    }) + rnorm(N, 0, sqrt(100-2^2*(k/2-floor(k/4))-sum(seq(7,7,length.out=10)[1:floor(k/4)])))
    z = rbinom(N, 1, 0.5)
    df = data.frame(y = y, z = z)
    df[df$z==1,"y"] = df[df$z==1,"y"] + 3
    df = cbind(df, data.frame(x))
    df
  })
  return(data)
}

sim_data2 = function(N, K = c(10, 20, 40), rho = 0.8){
  epsilon = matrix(rnorm(40*N), nrow = N)
  epsilon[,2*(1:10)] = 
    matrix(rpois(N*10, (10:1)*0.8), ncol = 10, byrow = TRUE)
  data = lapply(K, function(k){
    x = epsilon[,seq_len(k)]
    y = 3 + apply(x[,seq_len(k)], 1, function(i){
      sum(i[1:(k-8)]*2*rho^(0:(k-8-1))) +
            sum(i[(k-8+1):length(i)]*0.01*rho^((k-8):(length(i)-1)))
    }) + rnorm(N, 0, sqrt(70-sum((2*rho^(0:(k-8-1)))^2)-
                            sum((0.7*rho^((k+1):ncol(epsilon)))^2)))
    if(k < 40)
      y = y + apply(epsilon[,(k+1):ncol(epsilon)], 1, function(i){
      sum(i*0.7*rho^((k+1):ncol(epsilon)))
    })
    z = rbinom(N, 1, 0.5)
    df = data.frame(y = y, z = z)
    df[df$z==1,"y"] = df[df$z==1,"y"] + 3
    df = cbind(df, data.frame(x))
    df
  })
  return(data)
}
```

### Bias correction - Jackknife
```{r}
coef_jackknife = function(data, m = 20){
  data_ctl = data[data$z == 0,]
  fold = createFolds(1:nrow(data_ctl), m)
  beta_original = lm(y ~ . - z, data = data_ctl)$coefficients
  beta_jack = lapply(fold, function(i){
    lm(y ~ . - z, data = data_ctl[-i,])$coefficients
  })
  beta_jack = do.call("rbind", beta_jack)
  beta_crt = m * beta_original - (m-1)*apply(beta_jack, 2, mean)
  return(beta_crt)
}
```


### Regularization - Elastic Net
```{r}
coef_elastic_net = function(data){
  data_ctl = data[data$z == 0,]
  fit_en = cv.glmnet(
    as.matrix(data_ctl[,!colnames(data_ctl)%in%c("y","z")]),
    data_ctl[,"y"], 
    alpha = 0.5
  )
  beta_en = as.vector(coef(fit_en))
  return(beta_en)
}
```

### Causal effect
```{r}
causal_effect = function(data, beta){
  Y0 = sapply(1:nrow(data), function(i){
    beta[1] + 
      sum(beta[-1] * data[i,!colnames(data)%in%c("y","z")])
  })
  data$group = cut(Y0, 3)
  unadj = data %>% 
    group_by(group) %>% 
    summarise(ATE = sum(z*y)/sum(z) - sum((1-z)*y)/sum(1-z)) %>% 
    select(ATE) %>% 
    unlist()
  names(unadj) = c("low", "medium", "high")
  adj = sapply(levels(data$group), function(i){
    lm(y ~ ., 
       data = data[data$group == i, -ncol(data)])$coefficients["z"]
  })
  names(adj) = c("low", "medium", "high")
  return(c(unadj, adj))
}
```

```{r}
overall_effect = function(data){
  unadj = data %>% 
    summarise(sum(z*y)/sum(z) - sum((1-z)*y)/sum(1-z)) %>% 
    unlist()
  names(unadj) = "unadjusted"
  adj = lm(y ~ ., data = data)$coefficients["z"]
  names(adj) = "adjusted"
  return(c(unadj, adj))
}
```


## trial
### JTPA
```{r}
data = read.table("jtpa-1.csv")[,-c(1, 3)]
colnames(data) = c("y", "z", paste0("x", 1:15))
data = data[data$x1 == 1,]
data = data[,-3]
data = data[data$x2 %in% c(0,1) & data$x5 %in% c(0,1) 
            & data$x6 %in% c(0,1),]
overall = overall_effect(data)
data_ctl = data[data$z == 0,]
beta_original = lm(y ~ . - z, data = data_ctl)$coefficients
org = causal_effect(data, beta_original)
beta_jack = coef_jackknife(data, m = 3)
jackknife = causal_effect(data, beta_jack)
beta_en = coef_elastic_net(data)
elastic_net = causal_effect(data, beta_en)
result = rbind(org, jackknife, elastic_net)
```

```{r}
kable(result, "latex", booktabs = T, digits = 4,
      caption = "JTPA Estimation Results") %>% 
  add_header_above(c(" " = 1,"Unadjusted" = 3, "Adjusted" = 3)) %>% 
  kable_styling (position = "center")
kable(overall)
```


### simulated data
```{r}
S = 50
N = c(200, 500, 1000)
result_all = NULL
for(i in 1:length(N)){
  n = N[i]
  result_avg = matrix(0, nrow = 3, ncol = 18)
  success = 0
  for(j in 1:S){
    data_all = sim_data1(n)
    result_one = lapply(data_all, function(data){
      data_ctl = data[data$z == 0,]
      beta_original = lm(y ~ . - z, data = data_ctl)$coefficients
      org = causal_effect(data, beta_original)
      beta_jack = coef_jackknife(data, m = 3)
      jackknife = causal_effect(data, beta_jack)
      beta_en = coef_elastic_net(data)
      test = try(causal_effect(data, beta_en), silent=TRUE)
      elastic_net = if(class(test) %in% 'try-error') {return(NULL)} 
      else {causal_effect(data, beta_en)}
      rbind(org, jackknife, elastic_net)
    })
    result_one = do.call("cbind", result_one)
    if (ncol(result_one)==18){
      result_avg = result_avg + result_one
      success = success + 1
    }
  }
  result_avg = result_avg / success
  result_all = rbind(result_all, result_avg)
}
result1 = result_all
result1
```

```{r}
kable(result1, "latex", booktabs = T, digits = 4,
      caption = "Simulated Data Results") %>% 
  add_header_above(c(" " = 1, "Unadjusted" = 3, "Adjusted" = 3, 
                     "Unadjusted" = 3, "Adjusted" = 3, 
                     "Unadjusted" = 3, "Adjusted" = 3)) %>% 
  add_header_above(c(" " = 1, "K = 10" = 6, "K = 20" = 6, "K = 30" = 6)) %>% 
  group_rows("N = 200", 1, 3) %>% 
  group_rows("N = 500", 4, 6) %>% 
  group_rows("N = 1000", 7, 9) %>% 
  kable_styling (position = "center")
```

```{r}
S = 5
N = c(200, 500, 1000)
result_all = NULL
for(i in 1:length(N)){
  n = N[i]
  result_avg = matrix(0, nrow = 3, ncol = 18)
  for(j in 1:S){
    data_all = sim_data2(n)
    result_one = lapply(data_all, function(data){
      data_ctl = data[data$z == 0,]
      beta_original = lm(y ~ . - z, data = data_ctl)$coefficients
      org = causal_effect(data, beta_original)
      beta_jack = coef_jackknife(data, m = 3)
      jackknife = causal_effect(data, beta_jack)
      beta_en = coef_elastic_net(data)
      elastic_net = causal_effect(data, beta_en)
      rbind(org, jackknife, elastic_net)
    })
    result_avg = result_avg + do.call("cbind", result_one)
  }
  result_avg = result_avg / S
  result_all = rbind(result_all, result_avg)
}
result2 = result_all
```

